apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./manifests/admissionregistration.yaml
  - ./manifests/deployment.yaml
  - ./manifests/service.yaml
secretGenerator:
  - name: kube-admission
    files:
      - tls.crt=./manifests/ca.crt
      - tls.key=./manifests/ca.key
generatorOptions:
  disableNameSuffixHash: true
